Ap photogram ajax
APatel-AI/photogram-ajax pull request #1
Opened 2024-07-10 14:55 UTC by APatel-AI

2024-07-10 15:17 UTC, MayaS1111 approved these changes
Good job, but maybe make the small changes

2024-07-10 15:17 UTC, MayaS1111 commented on app/views/comments/edit.html.erb
I think you might need this....

2024-07-10 15:17 UTC, MayaS1111 commented on app/views/follow_requests/_follow_unfollow.html.erb
> +<div class = "<%= dom_id(sender)%>_<%=dom_id(recipient)%>_follow_unfollow">
Good job for having both the sender and recipient and using "class"

2024-07-10 15:17 UTC, MayaS1111 commented on app/views/follow_requests/create.js.erb
Cool idea adding using vars

2024-07-10 15:17 UTC, MayaS1111 commented on app/views/likes/_form.html.erb
> +    data: {remote: true}) do |form| %>  <%= form.hidden_field :fan_id %>
Dry up code. Use "local"

2024-07-10 15:17 UTC, MayaS1111 commented on app/views/likes/create.js.erb
> +var icon = $("#<%= dom_id(@like.photo)%>_likes_icon");
Not really needed, but cool

2024-07-10 15:17 UTC, MayaS1111 commented on app/views/likes/destroy.js.erb
> +var icon = $("#<%= dom_id(@like.photo)%>_likes_icon");
Same here

2024-07-10 20:36 UTC, ahuynh3a requested changes
Hi Arpan! You are off to a great start! Please make the changes accordingly and I can review/approve your pr! Please let me know if you have any questions!

2024-07-10 20:36 UTC, ahuynh3a commented on app/views/comments/create.js.erb
> +
please remove any unnecessary white space

2024-07-10 20:36 UTC, ahuynh3a commented on app/views/comments/edit.js.erb
> +var edited_comment = ("<%= j(render 'form', comment: @comment) %>");
Is this just 'form' or is it 'comment/form'

2024-07-10 20:36 UTC, ahuynh3a commented on app/views/comments/_form.html.erb
You are missing a unique id for the form here, which you will need to call in your update.js.erb

2024-07-10 20:36 UTC, ahuynh3a commented on app/views/comments/update.js.erb
> +$("#<%= dom_id(@comment) %>").replaceWith("<%= j(render @comment) %>");
hmm this isn't quite right. You are trying to replace the comment in the form so you must pull the unique id from the comments/_form (which you didn't create), let me know if you have questions about this!

2024-07-10 20:36 UTC, ahuynh3a commented on app/views/likes/_form.html.erb
> +<%= form_with(model: like, class: "d-inline-block",
this should just be remote: true

2024-07-11 14:29 UTC, dylansarikas commented on app/views/follow_requests/create.js.erb
Nice job creating for variables for this!  It makes the code much more readable!

2024-07-11 14:29 UTC, dylansarikas approved these changes
Looks good!

2024-07-11 20:05 UTC, ahuynh3a approved these changes
Thank you for making the changes!

2024-07-11 20:08 UTC, merged

2024-07-14 17:04 UTC, FadiBaker92 reviewed
Great job using variables, it makes the code easy to read. Looks good!